name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - run: yarn install --ignore-engines --ignore-scripts --frozen-lockfile

      - name: check Formatters
        run: yarn format:check

      - name: Run Linters
        run: yarn lint
